### ISSUE TITLE
Found no files with valid type definitions

### ISSUE THREAD

**Issue by koredefashokun** [danielrearden/sqlmancer#66]
I get this error when I try to start a server, using SQLMancer.

```
Error: Found no files with valid type definitions using glob pattern "/Users/korede/Overt/Market/server/src/schema.ts"
    at Object.createSqlmancerClient (/Users/korede/Overt/Market/server/node_modules/sqlmancer/src/client/createSqlmancerClient.ts:46:11)
    at Object.<anonymous> (/Users/korede/Overt/Market/server/src/database.ts:10:23)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Module.m._compile (/Users/korede/Overt/Market/server/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/korede/Overt/Market/server/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

Here's a [link to the code](https://github.com/overthq/Market/tree/master/server). This might not be an issue, but I'm not sure what I'm missing, since I followed the example. Any help is appreciated.

**Comment by danielrearden** [comment]
There's a missing semicolon here:

```
store: Store! @relate(on: [{ from "store_id", to: "id" }])
                                 ^
```

and an extraneous curly bracket here:

```
user: User! @relate(on: [{ from: "user_id", to: "id" }]})
                                                       ^
```

It would be helpful if the error message distinguished between "we didn't mind any type definitions" and "we found found type definitions but there were issues with them". I'd be even more helpful if the error message spelled out what was wrong with the type definitions. I opened #67 to track that fix.

Please let me know if you have any other questions or hit any other  obstacles!

**Comment by koredefashokun** [comment]
Thanks @danielrearden. Really appreciate this!
